"""
SQLAlchemy ORM models for AgentTrace server.

Two tables:
- Run   : one row per pipeline execution
- Step  : one row per agent invocation within a run
"""

from datetime import datetime
from sqlalchemy import (
    Column,
    String,
    Integer,
    Float,
    DateTime,
    ForeignKey,
    Text,
)
from sqlalchemy.orm import DeclarativeBase, relationship


class Base(DeclarativeBase):
    """Shared declarative base for all ORM models."""
    pass


class Run(Base):
    """
    Represents a single end-to-end pipeline execution.

    status is one of:
        "success"  — run completed without any step raising an exception
        "failed"   — the run raised an unhandled exception
        "partial"  — run exited before all steps completed (e.g. keyboard interrupt)
    """

    __tablename__ = "runs"

    id = Column(String(36), primary_key=True, comment="UUID4 generated by the SDK")
    pipeline_name = Column(String(255), nullable=False, index=True)
    started_at = Column(DateTime, nullable=False)
    ended_at = Column(DateTime, nullable=True)
    status = Column(String(16), nullable=False, default="partial")  # success | failed | partial
    total_cost_usd = Column(Float, nullable=True)
    total_tokens = Column(Integer, nullable=True)
    created_at = Column(DateTime, nullable=False, default=datetime.utcnow)

    # Relationship — gives us run.steps
    steps = relationship("Step", back_populates="run", order_by="Step.seq", cascade="all, delete-orphan")

    def __repr__(self) -> str:
        return f"<Run id={self.id!r} pipeline={self.pipeline_name!r} status={self.status!r}>"


class Step(Base):
    """
    Represents a single agent invocation captured by @trace_agent.

    seq is the 1-based call order within the parent run.
    """

    __tablename__ = "steps"

    id = Column(Integer, primary_key=True, autoincrement=True)
    run_id = Column(String(36), ForeignKey("runs.id", ondelete="CASCADE"), nullable=False, index=True)
    agent_name = Column(String(255), nullable=False)
    seq = Column(Integer, nullable=False, comment="1-based sequence within the run")
    input = Column(Text, nullable=True, comment="Serialized function args, truncated to 5000 chars")
    output = Column(Text, nullable=True, comment="Serialized return value, truncated to 5000 chars")
    error = Column(Text, nullable=True, comment="Exception message + traceback on failure")
    latency_ms = Column(Float, nullable=False)
    prompt_tokens = Column(Integer, nullable=True)
    completion_tokens = Column(Integer, nullable=True)
    cost_usd = Column(Float, nullable=True)
    status = Column(String(16), nullable=False, default="success")  # success | failed

    # Relationship back to parent run
    run = relationship("Run", back_populates="steps")

    def __repr__(self) -> str:
        return f"<Step id={self.id} run={self.run_id!r} agent={self.agent_name!r} seq={self.seq}>"
